version: '3.8'

services: 
  db-mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: db-mysql
    ports:
      - 3306:3306
    volumes:
      - ./db-mysql/data:/var/lib/mysql
  test-db-mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: test-db-mysql
    ports:
      - 3307:3306


volumes: 
  db-mysql:
    driver: local