version: '3.8'

services: 
  db: 
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports: 
      - 5432:5432
    volumes: 
      - ./db/data:/var/lib/postgresql/data
  test-db: 
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: user
      POSTGRES_DB: test-db
    ports: 
      - 5434:5432
  backup-db: 
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: user
      POSTGRES_DB: backup-db
      POSTGRES_MASTER_HOST: db 
      POSTGRES_MASTER_PORT: 5432
    volumes: 
      - ./backup-db/data:/var/lib/postgresql/data
    restart: always

volumes: 
  db: 
    driver: local
  backup-db:
    driver: local